# Generated by Django 4.0.2 on 2022-03-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruteurs',
            fields=[
                ('Id_Utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('Login', models.CharField(max_length=30, unique=True)),
                ('MDP', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30, unique=True)),
                ('Nom', models.CharField(max_length=30)),
                ('Tel', models.IntegerField(unique=True)),
                ('Gouvernorat', models.CharField(max_length=30)),
                ('Adresse', models.CharField(max_length=30)),
                ('CodePostal', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('Id_Utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('Login', models.CharField(max_length=30, unique=True)),
                ('MDP', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30, unique=True)),
                ('Nom', models.CharField(max_length=30)),
                ('Tel', models.IntegerField(unique=True)),
                ('Gouvernorat', models.CharField(max_length=30)),
                ('Adresse', models.CharField(max_length=30)),
                ('DDN', models.DateField()),
                ('Civilité', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
