# Generated by Django 4.0.3 on 2022-03-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruteurs',
            fields=[
                ('RecruteurId', models.AutoField(primary_key=True, serialize=False)),
                ('RecruteurName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=100)),
            ],
        ),
    ]
