# Generated by Django 4.0.2 on 2022-03-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='Civilité',
            new_name='Civ',
        ),
    ]
