# Generated by Django 4.0.2 on 2022-05-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intersuj',
            name='id_agenda',
        ),
    ]
