# Generated by Django 4.0.3 on 2022-04-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePass',
            fields=[
                ('Id_MDP', models.AutoField(primary_key=True, serialize=False)),
                ('Login', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('MDP', models.CharField(max_length=30)),
            ],
        ),
    ]
