# Generated by Django 4.0.2 on 2022-04-14 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intersuj',
            old_name='inter',
            new_name='Att',
        ),
        migrations.RemoveField(
            model_name='intersuj',
            name='id_agenda',
        ),
    ]
