# Generated by Django 4.0.2 on 2022-04-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0002_rename_inter_intersuj_att_remove_intersuj_id_agenda'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='intersuj',
            unique_together={('student', 'recruteur', 'id_sujet')},
        ),
    ]
