# Generated by Django 4.0.2 on 2022-03-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0002_rename_civilité_students_civ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruteurs',
            name='Tel',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='DDN',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='Tel',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
