# Generated by Django 4.0.2 on 2022-04-15 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0003_alter_intersuj_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackEtudEntr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeedBack', models.TextField()),
                ('Rating', models.IntegerField()),
                ('Recruteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PcdApp.recruteurs')),
            ],
        ),
    ]
