# Generated by Django 4.0.3 on 2022-04-10 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0004_alter_recruteurs_codepostal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('LoginStu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PcdApp.students')),
                ('Formation', models.CharField(max_length=250)),
                ('ExpProf', models.CharField(max_length=250)),
                ('Certif', models.CharField(max_length=250)),
                ('Lang', models.CharField(max_length=250)),
                ('Liens', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('LoginStu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PcdApp.students')),
                ('InfoPer', models.TextField()),
                ('Compe', models.TextField()),
                ('InfoAdd', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackRec',
            fields=[
                ('Login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PcdApp.recruteurs')),
                ('Email', models.CharField(max_length=30, unique=True)),
                ('Message', models.TextField()),
                ('Rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InfoAdd',
            fields=[
                ('LoginStu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PcdApp.students')),
                ('CentreInt', models.CharField(max_length=250)),
                ('VieAsso', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='InfoPer',
            fields=[
                ('LoginStu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PcdApp.students')),
                ('Nom', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30, unique=True)),
                ('Tel', models.CharField(max_length=10, unique=True)),
                ('Gouvernorat', models.CharField(max_length=30)),
                ('Adresse', models.CharField(max_length=30)),
                ('DDN', models.CharField(max_length=30)),
                ('Dom', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('Id_sujet', models.AutoField(primary_key=True, serialize=False)),
                ('Titre', models.TextField()),
                ('Description', models.TextField()),
                ('Domaine', models.TextField()),
                ('duree', models.TextField()),
                ('Tech', models.TextField()),
                ('paye', models.BooleanField(default=False)),
                ('Bin', models.BooleanField(default=False)),
                ('Att', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='recruteurs',
            name='Id_Utilisateur',
        ),
        migrations.RemoveField(
            model_name='students',
            name='Id_Utilisateur',
        ),
        migrations.AlterField(
            model_name='recruteurs',
            name='Login',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='Login',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('Id_Calend', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.CharField(max_length=10)),
                ('StartTime', models.CharField(max_length=5)),
                ('EndTime', models.CharField(max_length=5)),
                ('LoginRec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PcdApp.recruteurs')),
            ],
        ),
    ]
