# Generated by Django 4.0.3 on 2022-03-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0004_alter_recruteurs_codepostal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('Id_Com', models.AutoField(primary_key=True, serialize=False)),
                ('Formation', models.CharField(max_length=250)),
                ('ExpProf', models.CharField(max_length=250)),
                ('Certif', models.CharField(max_length=250)),
                ('Lang', models.CharField(max_length=250)),
                ('Liens', models.CharField(max_length=250)),
                ('Dom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('Id_Cv', models.AutoField(primary_key=True, serialize=False)),
                ('InfoPer', models.TextField()),
                ('Compe', models.TextField()),
                ('InfoAdd', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InfoAdd',
            fields=[
                ('Id_InfoAdd', models.AutoField(primary_key=True, serialize=False)),
                ('CentreInt', models.CharField(max_length=250)),
                ('VieAsso', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='InfoPer',
            fields=[
                ('Id_InfoPer', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30, unique=True)),
                ('Tel', models.CharField(max_length=10, unique=True)),
                ('Gouvernorat', models.CharField(max_length=30)),
                ('Adresse', models.CharField(max_length=30)),
                ('DDN', models.CharField(max_length=30)),
            ],
        ),
    ]
