# Generated by Django 4.0.3 on 2022-03-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0004_alter_recruteurs_codepostal'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30, unique=True)),
                ('Tel', models.CharField(max_length=10, unique=True)),
                ('Gouvernorat', models.CharField(max_length=30)),
                ('Adresse', models.CharField(max_length=30)),
                ('DDN', models.CharField(max_length=30)),
                ('Id_InfoPer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PcdApp.students', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CentreInt', models.CharField(max_length=250)),
                ('VieAsso', models.CharField(max_length=250)),
                ('Id_InfoAdd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PcdApp.students', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InfoPer', models.TextField()),
                ('Compe', models.TextField()),
                ('InfoAdd', models.TextField()),
                ('Id_Cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PcdApp.students', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Formation', models.CharField(max_length=250)),
                ('ExpProf', models.CharField(max_length=250)),
                ('Certif', models.CharField(max_length=250)),
                ('Lang', models.CharField(max_length=250)),
                ('Liens', models.CharField(max_length=250)),
                ('Id_Com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PcdApp.students', unique=True)),
            ],
        ),
    ]
