# Generated by Django 4.0.3 on 2022-04-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0005_competence_cv_infoadd_infoper_sujet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='Att',
            field=models.BooleanField(default=False),
        ),
    ]
