# Generated by Django 4.0.3 on 2022-04-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0005_competence_cv_infoadd_infoper'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Prenom',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
