# Generated by Django 4.0.2 on 2022-04-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0005_competence_cv_infoadd_infoper_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('Id_sujet', models.AutoField(primary_key=True, serialize=False)),
                ('Titre', models.TextField()),
                ('Description', models.TextField()),
                ('Domaine', models.TextField()),
                ('duree', models.TextField()),
                ('Tech', models.TextField()),
                ('paye', models.BooleanField(default=False)),
                ('Bin', models.BooleanField(default=False)),
                ('Att', models.BooleanField(default=False)),
            ],
        ),
    ]
