# Generated by Django 4.0.2 on 2022-04-09 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0006_sujet'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackRec',
            fields=[
                ('Login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PcdApp.recruteurs')),
                ('Email', models.CharField(max_length=30, unique=True)),
                ('Message', models.TextField()),
                ('Rating', models.IntegerField()),
            ],
        ),
    ]
