# Generated by Django 4.0.3 on 2022-04-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0006_students_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Prenom',
            field=models.CharField(default='test', max_length=30),
        ),
    ]
