# Generated by Django 4.0.3 on 2022-04-03 14:56

import PcdApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0007_alter_students_prenom'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadImage',
            fields=[
                ('Id_Image', models.AutoField(primary_key=True, serialize=False)),
                ('Login', models.CharField(max_length=30, unique=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to=PcdApp.models.uploadFile)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='Prenom',
            field=models.CharField(max_length=30),
        ),
    ]
