# Generated by Django 4.0.2 on 2022-04-09 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0007_feedbackrec'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='LoginRec',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PcdApp.recruteurs'),
        ),
    ]
