# Generated by Django 4.0.2 on 2022-04-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0008_sujet_loginrec'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruteurs',
            name='Domaine',
            field=models.CharField(default='', max_length=30),
        ),
    ]
