# Generated by Django 4.0.3 on 2022-04-05 23:05

import PcdApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0008_uploadimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('Id_PDF', models.AutoField(primary_key=True, serialize=False)),
                ('Login', models.CharField(max_length=30)),
                ('PDF', models.FileField(blank=True, null=True, upload_to=PcdApp.models.uploadFile)),
            ],
        ),
    ]
