# Generated by Django 4.0.2 on 2022-04-11 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0010_suit_students_follow_suit_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suit',
            name='id_agenda',
        ),
        migrations.RemoveField(
            model_name='suit',
            name='id_sujet',
        ),
        migrations.CreateModel(
            name='InterSuj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inter', models.BooleanField(blank=True, default=False)),
                ('id_agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PcdApp.agenda')),
                ('id_sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PcdApp.sujet')),
                ('recruteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PcdApp.recruteurs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PcdApp.students')),
            ],
        ),
    ]
