# Generated by Django 4.0.2 on 2022-04-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PcdApp', '0011_remove_suit_id_agenda_remove_suit_id_sujet_intersuj'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='suit',
            unique_together={('student', 'recruteur')},
        ),
    ]
